In [89]:
# 1. Завантаження та огляд

import pandas as pd

df = pd.read_csv("tip.csv")

# Перші 5 рядків
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [90]:
# Розмір датасету (shape)
df.shape

(244, 7)

In [7]:
# Назви всіх колонок
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [91]:
# Інформацію про типи даних (info)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [92]:
# 2. Базова вибірка даних

# Колонку total_bill (загальний рахунок)
total_bill = df['total_bill']
total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [93]:
# Колонки total_bill та tip (чайові) разом
two_col = df[["total_bill", 'tip']]
two_col

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [94]:
# Перші 10 рядків
df.iloc[0:10]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [95]:
# Рядок з індексом 5
df.loc[5]

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

In [98]:
# 3. Фільтрація даних

# Всі рахунки більше 20 доларів (total_bill > 20)
more_20 = df[df["total_bill"] > 20]
print(f"There are {len(more_20)} bills.\n \nFirst five bills:")
display(more_20.iloc[0:5])

There are 97 bills.

First five bills:

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

In [100]:
# Всі відвідувачі-жінки (sex == 'Female')
women = df[df["sex"] == "Female"]
print(f"Total female bills: {len(women)}. \n\nFirst 5 rows:")
display(women.iloc[0:5])

Total female bills: 87.

First 5 rows:

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [101]:
# Рахунки на вечерю (time == 'Dinner')
dinner = df[df["time"] == "Dinner"]
print(f"All bills for dinner: {len(dinner)}. \n\nFirst 5 rows:")
display(dinner.iloc[0:5])

All bills for dinner: 176.

First 5 rows:

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [102]:
# Рахунки на вечерю з сумою чеку більше 30 доларів
dinner_30 = df[(df["time"] == "Dinner") & (df["total_bill"] > 30)]
print(f"Dinner bills over 30 dollars: {len(dinner_30)}. \n\nFirst 5 rows:")
display(dinner_30.iloc[0:5])

Dinner bills over 30 dollars: 27.

First 5 rows:

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

In [103]:
# 4. Описова статистика
# Середній розмір рахунку на всьому наборі даних
print(f"Average bill: {df["total_bill"].mean().round(2)} dollars")

Average bill: 19.79 dollars

In [104]:
# Максимальні чайові
print(f"Max tips: {df["tip"].max().round(2)} dollars.")

Max tips: 10.0 dollars.

In [105]:
# Кількість пропущених значень у всіх колонках
print(f"Empty rows: \n\n{df.isna().sum()}")

Empty rows:

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [106]:
# Скільки в наборі даних рахунківи і за вечері за обід
df.time.unique() #я не знаю, як вони написали "вечері", тому перевіряю

<StringArray>
['Dinner', 'Lunch']
Length: 2, dtype: str

In [107]:
bils_lun = df[df["time"] == "Lunch"]
bils_din = df[df["time"] == "Dinner"]
print(f"Bills in dinners {len(bils_din)} and lunches {len(bils_lun)} ")

Bills in dinners 176 and lunches 68

In [108]:
# Або просто порахувати з .value_counts():
print(f"Total amount of bills by {df["time"].value_counts()}")

Total amount of bills by time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [109]:
# 5. Статистика із групуванням
# Середній рахунок за статтю (groupby sex)
mean_bysex = df.groupby("sex")["total_bill"].mean()
print(f"Mean bill by {mean_bysex}")

Mean bill by sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

In [110]:
# Середні чайові за днем тижня (groupby day)
mean_tips = df.groupby("day")["tip"].mean().round(2)
print(f"Average tips by: {mean_tips}")

Average tips by: day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [111]:
# Скільки відвідувачів у кожен день
day_people = df.groupby("day")["size"].sum()
print(f"Total visitors per {day_people}")

Total visitors per day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

In [112]:
# 6. Створення нової колонки
df["tip_percentage"] = df["tip"] * 100 / df["total_bill"]
df.head(10)

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765
5       25.29  4.71    Male     No  Sun  Dinner     4       18.623962
6        8.77  2.00    Male     No  Sun  Dinner     2       22.805017
7       26.88  3.12    Male     No  Sun  Dinner     4       11.607143
8       15.04  1.96    Male     No  Sun  Dinner     2       13.031915
9       14.78  3.23    Male     No  Sun  Dinner     2       21.853857

In [113]:
# 7. Сортування
# За розміром рахунку (зростання)
df_sorted_bill = df.sort_values("total_bill")
df_sorted_bill.head()

     total_bill   tip     sex smoker   day    time  size  tip_percentage
67         3.07  1.00  Female    Yes   Sat  Dinner     1       32.573290
92         5.75  1.00  Female    Yes   Fri  Dinner     2       17.391304
111        7.25  1.00  Female     No   Sat  Dinner     1       13.793103
172        7.25  5.15    Male    Yes   Sun  Dinner     2       71.034483
149        7.51  2.00    Male     No  Thur   Lunch     2       26.631158

In [114]:
# За чайовими (спадання)
df_sorted_tips = df.sort_values("tip", ascending=False)
df_sorted_tips.head()

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3       19.681165
212       48.33   9.00  Male     No   Sat  Dinner     4       18.621974
23        39.42   7.58  Male     No   Sat  Dinner     4       19.228818
59        48.27   6.73  Male     No   Sat  Dinner     4       13.942407
141       34.30   6.70  Male     No  Thur   Lunch     6       19.533528

In [115]:
# Додатково виведіть топ-5 найбільших чайових використовуючи метод nlargest.
df_top_5_tips = df.nlargest(5, "tip")
df_top_5_tips

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3       19.681165
212       48.33   9.00  Male     No   Sat  Dinner     4       18.621974
23        39.42   7.58  Male     No   Sat  Dinner     4       19.228818
59        48.27   6.73  Male     No   Sat  Dinner     4       13.942407
141       34.30   6.70  Male     No  Thur   Lunch     6       19.533528